name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master

pr:
  - master

resources:
  - repo: self

variables:
  - template: variables.yaml



stages:
  - stage: Tag
    displayName: Semantic release
    pool:
        vmImage: 'vs2017-win2016'
    jobs:
    - job: Build
      pool:
        vmImage: 'vs2017-win2016'
      steps:

      - script: >
          npx -p semantic-release
          -p @semantic-release/git
          -p semantic-release-ado
          semantic-release
        env: { GH_TOKEN: 7a17c5d67b7db5c7180ea3443c8bbfcfd103236b }
        displayName: 'Semantic release'

      - script: echo $(nextRelease)
        displayName: 'Show next version'

