name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master

pr:
  - master

resources:
  - repo: self

stages:
  - stage: Tag
    displayName: Semantic release
    pool:
        vmImage: 'vs2017-win2016'
    jobs:
    - job: Build
      pool:
        vmImage: 'vs2017-win2016'
      steps:

      - script: >
          npx -p semantic-release
          -p @semantic-release/git
          -p semantic-release-ado
          semantic-release
        env: { GH_TOKEN: $(GitHubToken) }
        displayName: 'Semantic release'

      - script: echo $(Semantic release.nextRelease)
        displayName: 'Show next version'

