name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master

pr:
  - master

resources:
  - repo: self

stages:
  - stage: Tag
    displayName: Semantic release
    pool:
        vmImage: 'vs2017-win2016'
    jobs:
    - job: Build
      pool:
        vmImage: 'vs2017-win2016'
      steps:
      - script:  >
          npx 
          -p semantic-release
          -p @semantic-release/changelog
          -p @semantic-release/git
          -p semantic-release-ado
          semantic-release
        displayName: 'Tag release (semantic)'
        env: { GH_TOKEN: $(GitHubToken) }
      - script: echo $(nextRelease)
#      - script: npx -p semantic-release -p @semantic-release/git  -p semantic-release-ado  semantic-release && echo "##vso[task.setvariable variable=versionNumber]$(nextRelease) && echo "##vso[task.setvariable variable=_NEXT_RELEASE_TAG]$(cat VERSION.txt)" && echo "##vso[task.setvariable variable=_CURRENT_RELEASE_TAG]$(cat CURRENT.txt)"
#        env: { GH_TOKEN: $(GitHubToken) }
#        displayName: 'Semantic release'
#        name: semantic

      - script: echo $(versionNumber)-$(_NEXT_RELEASE_TAG)-$(_CURRENT_RELEASE_TAG)
        displayName: 'Show next version'


#      - powershell: |
#          echo "##vso[task.setvariable variable=versionNumber;isOutput=true]$(nextRelease)"
#        name: setOutputVar

#    - job: Job2
#      dependsOn: Build
#      pool:
#        vmImage: 'vs2017-win2016'
#      variables:
#        versionNumber: $[ dependencies.Build.outputs['setOutputVar.versionNumber'] ]
    
#      steps:
#      - script: echo $(versionNumber)
#        displayName: 'Show next version'