name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master

pr:
  - master

resources:
  - repo: self

stages:
  - stage: Tag
    displayName: Semantic release
    pool:
        vmImage: 'vs2017-win2016'
    jobs:
    - job: Build
      pool:
        vmImage: 'vs2017-win2016'
      steps:

      - script: >
          echo "TEEESTTTTTT LINEEEEEEE"; npx -p semantic-release -p @semantic-release/git  -p semantic-release-ado  semantic-release; echo "HELLOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"; echo "##vso[task.setvariable variable=versionNumber]$(nextRelease)"
        env: { GH_TOKEN: $(GitHubToken) }
        displayName: 'Semantic release'
        name: semantic

      - script: echo $(versionNumber)
        displayName: 'Show next version'


#      - powershell: |
#          echo "##vso[task.setvariable variable=versionNumber;isOutput=true]$(nextRelease)"
#        name: setOutputVar

#    - job: Job2
#      dependsOn: Build
#      pool:
#        vmImage: 'vs2017-win2016'
#      variables:
#        versionNumber: $[ dependencies.Build.outputs['setOutputVar.versionNumber'] ]
    
#      steps:
#      - script: echo $(versionNumber)
#        displayName: 'Show next version'